### ISSUE TITLE
Not compatible with BepInEx 6.0.0-pre.1

### ISSUE THREAD

**Issue by fleps** [pangliang/Cities-Skyline2-Mods#1]
I'm already using a mod/plugin that has a dependency of [BepInEx 6.0.0-pre.1](https://github.com/BepInEx/BepInEx/releases/tag/v6.0.0-pre.1).

I tested one of your mods (the one that makes the road marks more subtle) and doesn't work/load, the BepInEx windows shows only the other mod being loaded.

Consider making the mods compatible with v6 as it looks like it's already being used by other mods and v5 is now in LTS

**Comment by pangliang** [comment]
Yes, the version I am currently publishing is based on BepInEx 5, but if you want to support BepInEx 6, it is also very simple. Change the `BepInEx.Core` referenced by the package to `BepInEx.Unity` version designation `6.0.0-pre.*`, and recompile

You can also directly use the BepInEx6 version I just submitted. They are in the attachment on the release page.

```
<PackageReference Include="BepInEx.Core" Version="5.*" IncludeAssets="compile" />
# change to
<PackageReference Include="BepInEx.Unity" Version="6.0.0-pre.*" IncludeAssets="compile" />
````

**Comment by fleps** [comment]
Thanks for the release for v6, but I tested TrafficReduction and doesn't load, the BepInEx window doesn't even see it.

I tested removing the other mod I have been using and leave only yours, BEx says "0 plugins to load", no error or anything on the logs.

When I use the other mod, this is what I see on the window/logs:

```
[Message: Preloader] BepInEx 6.0.0-be.674 - Cities2
[Message: Preloader] Built from commit 82077ec7c91c97f0e5f8ada5d178fd7ece6c0099
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity 2022.3.7f1
[Info   : Preloader] CLR runtime version: 4.0.30319.42000
[Info   : Preloader] Supports SRE: True
[Message: Preloader] Preloader started
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInEx.Unity.Mono.Preloader 6.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 178 assemblies discovered
[Message:AssemblyPatcher] Executing 1 patch(es)
[Message: Preloader] Preloader finished
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [CustomTreeGrowth 1.0.0]
[Info   :   Console] Logs at C:/Users/flep/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs
[Info   :CustomTreeGrowth] Plugin CustomTreeGrowth is loaded! Patched methods: 6
[Info   :CustomTreeGrowth] Patched method: Game.dll:OnCreate
[Info   :CustomTreeGrowth] Patched method: Game.dll:OnUpdate
[Info   :CustomTreeGrowth] Patched method: Game.dll:OnCreateForCompiler
[Info   :CustomTreeGrowth] Patched method: Game.dll:OnGameLoadingComplete
[Info   :CustomTreeGrowth] Patched method: Game.dll:ParseOptions
[Info   :CustomTreeGrowth] Patched method: Game.dll:UpdateInfoviewColors
[Message:   BepInEx] Chainloader startup complete
```


Cheers.

**Comment by pangliang** [comment]
You are using version `BepInEx 6.0.0-be` , not version `BepInEx 6.0.0-pre` ; according to the release instructions, the loading methods of `be` and `pre` versions are different.

I did not test yesterday's release, and it is possible that the nuget restore was not completed correctly. I recompiled and the test passed on my side. I republished the compressed package into the release, `xxx_BeInEx_6.zip` replaced `xxx_BeInEx6.zip`,

Anyway, first reinstall the correct BeInEx-6.0.0-pre and try again

**Comment by fleps** [comment]
You are correct, my bad, I'm new to the whole BIEx Unity plugin thing.
The other mods on the site (same place where you uploaded your plugins) that mentioned BepInEx v6 are using/linking to the -be version, not pre.

Your new versions loaded properly with the pre version, sadly the other mods not, they only work with the be version.

I'll report to them about this too but for now will need to stick to the v6 be version to keep using the other mods.

Thanks, this can be closed.
